/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    pages: Page;
    menu: Menu;
    footer: Footer;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'hr' | 'de';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage user accounts and permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'superadmin' | 'tenant-admin';
  tenant?: (string | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Manage tenant organizations (hotels, restaurants, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  subdomain: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage images, documents and other media files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  tenant?: (string | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage pages for tenants and main domain
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  tenant?: (string | null) | Tenant;
  layout?:
    | (
        | {
            /**
             * Make this section take up the full viewport height
             */
            isFullHeight?: boolean | null;
            /**
             * Choose the container width for section content
             */
            container?: ('full' | 'container') | null;
            /**
             * CSS color value (e.g., #000000, rgb(0,0,0), black)
             */
            backgroundColor?: string | null;
            backgroundMedia?: {
              type?: ('none' | 'image' | 'video') | null;
              image?: (string | null) | Media;
              video?: (string | null) | Media;
              overlay?: ('none' | 'light' | 'medium' | 'dark') | null;
            };
            padding?: {
              top?: number | null;
              right?: number | null;
              bottom?: number | null;
              left?: number | null;
            };
            blocks?:
              | (
                  | {
                      heading: string;
                      subheading?: string | null;
                      /**
                       * Optional ID for this section (used for menu navigation)
                       */
                      sectionId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'hero';
                    }
                  | {
                      heading?: string | null;
                      features?:
                        | {
                            title?: string | null;
                            description?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      /**
                       * Optional ID for this section (used for menu navigation)
                       */
                      sectionId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'features';
                    }
                  | {
                      heading: string;
                      content: {
                        root: {
                          type: string;
                          children: {
                            type: string;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      /**
                       * Optional ID for this section (used for menu navigation)
                       */
                      sectionId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'text';
                    }
                  | {
                      columns?:
                        | {
                            title: string;
                            subtitle?: string | null;
                            /**
                             * Optional background image for this column
                             */
                            backgroundImage?: (string | null) | Media;
                            /**
                             * Make this column take the full viewport height
                             */
                            fullHeight?: boolean | null;
                            /**
                             * Optional gradient overlay for this column
                             */
                            gradient?: {
                              enabled?: boolean | null;
                              type?: ('linear' | 'radial') | null;
                              direction?:
                                | (
                                    | 'to-bottom'
                                    | 'to-top'
                                    | 'to-right'
                                    | 'to-left'
                                    | 'to-bottom-right'
                                    | 'to-bottom-left'
                                    | 'to-top-right'
                                    | 'to-top-left'
                                  )
                                | null;
                              position?:
                                | (
                                    | 'center'
                                    | 'top'
                                    | 'bottom'
                                    | 'left'
                                    | 'right'
                                    | 'top-left'
                                    | 'top-right'
                                    | 'bottom-left'
                                    | 'bottom-right'
                                  )
                                | null;
                              /**
                               * Hex color code (e.g., #000000)
                               */
                              startColor?: string | null;
                              /**
                               * Hex color code (e.g., #ffffff)
                               */
                              endColor?: string | null;
                              /**
                               * Gradient opacity (0 = transparent, 1 = opaque)
                               */
                              opacity?: number | null;
                            };
                            link: {
                              url: string;
                              text: string;
                              openInNewTab?: boolean | null;
                            };
                            /**
                             * Optional social network links for this column
                             */
                            socialNetworks?: {
                              /**
                               * Full Facebook profile or page URL
                               */
                              facebook?: string | null;
                              /**
                               * Full Instagram profile URL
                               */
                              instagram?: string | null;
                            };
                            id?: string | null;
                          }[]
                        | null;
                      /**
                       * Optional ID for this section (used for menu navigation)
                       */
                      sectionId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'three-columns';
                    }
                )[]
              | null;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            heading: string;
            subheading?: string | null;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            features?:
              | {
                  title?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            heading: string;
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            columns?:
              | {
                  title: string;
                  subtitle?: string | null;
                  /**
                   * Optional background image for this column
                   */
                  backgroundImage?: (string | null) | Media;
                  /**
                   * Make this column take the full viewport height
                   */
                  fullHeight?: boolean | null;
                  /**
                   * Optional gradient overlay for this column
                   */
                  gradient?: {
                    enabled?: boolean | null;
                    type?: ('linear' | 'radial') | null;
                    direction?:
                      | (
                          | 'to-bottom'
                          | 'to-top'
                          | 'to-right'
                          | 'to-left'
                          | 'to-bottom-right'
                          | 'to-bottom-left'
                          | 'to-top-right'
                          | 'to-top-left'
                        )
                      | null;
                    position?:
                      | (
                          | 'center'
                          | 'top'
                          | 'bottom'
                          | 'left'
                          | 'right'
                          | 'top-left'
                          | 'top-right'
                          | 'bottom-left'
                          | 'bottom-right'
                        )
                      | null;
                    /**
                     * Hex color code (e.g., #000000)
                     */
                    startColor?: string | null;
                    /**
                     * Hex color code (e.g., #ffffff)
                     */
                    endColor?: string | null;
                    /**
                     * Gradient opacity (0 = transparent, 1 = opaque)
                     */
                    opacity?: number | null;
                  };
                  link: {
                    url: string;
                    text: string;
                    openInNewTab?: boolean | null;
                  };
                  /**
                   * Optional social network links for this column
                   */
                  socialNetworks?: {
                    /**
                     * Full Facebook profile or page URL
                     */
                    facebook?: string | null;
                    /**
                     * Full Instagram profile URL
                     */
                    instagram?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'three-columns';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage navigation menus for tenants and main domain
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  /**
   * Unique identifier for this menu type. Main Menu gets centered logo styling, Tenant Menu gets standard top-left styling.
   */
  identifier: 'main-menu' | 'tenant-menu';
  /**
   * Internal title for this menu (e.g., "Hotel ABC Menu", "Restaurant XYZ Menu")
   */
  title: string;
  tenant?: (string | null) | Tenant;
  menuItems?:
    | {
        label: string;
        /**
         * URL or path for this menu item (required even if using scroll target)
         */
        link: string;
        /**
         * Optional section ID to scroll to (e.g., "hero", "features"). Leave empty to use the link above.
         */
        scrollTarget?: string | null;
        external?: boolean | null;
        children?:
          | {
              label: string;
              /**
               * URL or path for this menu item (required even if using scroll target)
               */
              link: string;
              /**
               * Optional section ID to scroll to (e.g., "hero", "features"). Leave empty to use the link above.
               */
              scrollTarget?: string | null;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  logo?: (string | null) | Media;
  logoText?: string | null;
  /**
   * Choose how the menu should be positioned on the page
   */
  positioning?: ('fixed' | 'absolute' | 'relative') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage footer content for tenants and main domain
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Internal title for this footer (e.g., "Hotel ABC Footer", "Restaurant XYZ Footer")
   */
  title: string;
  tenant?: (string | null) | Tenant;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              link: string;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomSection?: {
    copyright?: string | null;
    socialLinks?:
      | {
          platform?: ('facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube') | null;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'menu';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'footer';
        value: string | Footer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  subdomain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tenant?: T;
  layout?:
    | T
    | {
        section?:
          | T
          | {
              isFullHeight?: T;
              container?: T;
              backgroundColor?: T;
              backgroundMedia?:
                | T
                | {
                    type?: T;
                    image?: T;
                    video?: T;
                    overlay?: T;
                  };
              padding?:
                | T
                | {
                    top?: T;
                    right?: T;
                    bottom?: T;
                    left?: T;
                  };
              blocks?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          heading?: T;
                          subheading?: T;
                          sectionId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    features?:
                      | T
                      | {
                          heading?: T;
                          features?:
                            | T
                            | {
                                title?: T;
                                description?: T;
                                id?: T;
                              };
                          sectionId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    text?:
                      | T
                      | {
                          heading?: T;
                          content?: T;
                          sectionId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    'three-columns'?:
                      | T
                      | {
                          columns?:
                            | T
                            | {
                                title?: T;
                                subtitle?: T;
                                backgroundImage?: T;
                                fullHeight?: T;
                                gradient?:
                                  | T
                                  | {
                                      enabled?: T;
                                      type?: T;
                                      direction?: T;
                                      position?: T;
                                      startColor?: T;
                                      endColor?: T;
                                      opacity?: T;
                                    };
                                link?:
                                  | T
                                  | {
                                      url?: T;
                                      text?: T;
                                      openInNewTab?: T;
                                    };
                                socialNetworks?:
                                  | T
                                  | {
                                      facebook?: T;
                                      instagram?: T;
                                    };
                                id?: T;
                              };
                          sectionId?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              heading?: T;
              content?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'three-columns'?:
          | T
          | {
              columns?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    backgroundImage?: T;
                    fullHeight?: T;
                    gradient?:
                      | T
                      | {
                          enabled?: T;
                          type?: T;
                          direction?: T;
                          position?: T;
                          startColor?: T;
                          endColor?: T;
                          opacity?: T;
                        };
                    link?:
                      | T
                      | {
                          url?: T;
                          text?: T;
                          openInNewTab?: T;
                        };
                    socialNetworks?:
                      | T
                      | {
                          facebook?: T;
                          instagram?: T;
                        };
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  identifier?: T;
  title?: T;
  tenant?: T;
  menuItems?:
    | T
    | {
        label?: T;
        link?: T;
        scrollTarget?: T;
        external?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              scrollTarget?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  logo?: T;
  logoText?: T;
  positioning?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  tenant?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  bottomSection?:
    | T
    | {
        copyright?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}