/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    tenants: Tenant;
    pages: Page;
    menu: Menu;
    footer: Footer;
    buildings: Building;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    buildings: BuildingsSelect<false> | BuildingsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('hr' | 'en' | 'de') | ('hr' | 'en' | 'de')[];
  globals: {};
  globalsSelect: {};
  locale: 'hr' | 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage user accounts and permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'superadmin' | 'tenant-admin';
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage tenant organizations (hotels, restaurants, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  subdomain: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage images, documents and other media files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    xs?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xxl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait34?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    landscape43?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    landscape169?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * PDF documents only. Upload unit-details PDFs here. For Buildings, use "Unit details PDF" or add a document from this collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Optional label (e.g. "Unit details – Building A")
   */
  title?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Pages for tenants and main domain. Layout blocks are grouped in the editor: District · Real estate (RE landing + legacy RE), District · Boutique, District · Momento (reserved), District · Hub & pages. RE landing form and contact row: edit “RE Landing — Inquiry” in the page layout. The RE landing strip footer is edited in the Footers collection (not in the page layout).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  tenant?: (number | null) | Tenant;
  layout?:
    | (
        | {
            heading: string;
            /**
             * Boutique hero: optional eyebrow, then a line with only ---, then body text. Heading: word *Boutique* is auto-accented; use *like this* for other italics.
             */
            subheading?: string | null;
            backgroundMedia?: {
              type?: ('none' | 'image' | 'video') | null;
              image?: (number | null) | Media;
              video?: (number | null) | Media;
              overlay?: ('none' | 'light' | 'medium' | 'dark') | null;
            };
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            features?:
              | {
                  title?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            content: string;
            /**
             * Choose the font size for the text content
             */
            fontSize?: ('small' | 'medium' | 'large' | 'xl') | null;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            columns?:
              | {
                  title: string;
                  /**
                   * Short paragraph shown on the column (revealed on hover on desktop).
                   */
                  subtitle?: string | null;
                  /**
                   * Small uppercase line above the title (e.g. Rooms · Rooftop · Pool).
                   */
                  kicker?: string | null;
                  /**
                   * Optional label with gold line (e.g. 01 / Hotel). Leave empty to auto-fill as 01, 02, 03.
                   */
                  numberLabel?: string | null;
                  /**
                   * Optional second part of the title in gold italic (e.g. "." or "Estate."). Main title field stays the first word(s).
                   */
                  titleItalic?: string | null;
                  /**
                   * Optional background image for this column
                   */
                  backgroundImage?: (number | null) | Media;
                  /**
                   * Make this column take the full viewport height
                   */
                  fullHeight?: boolean | null;
                  /**
                   * Optional gradient overlay for this column
                   */
                  gradient?: {
                    enabled?: boolean | null;
                    type?: ('linear' | 'radial') | null;
                    direction?:
                      | (
                          | 'to-bottom'
                          | 'to-top'
                          | 'to-right'
                          | 'to-left'
                          | 'to-bottom-right'
                          | 'to-bottom-left'
                          | 'to-top-right'
                          | 'to-top-left'
                        )
                      | null;
                    position?:
                      | (
                          | 'center'
                          | 'top'
                          | 'bottom'
                          | 'left'
                          | 'right'
                          | 'top-left'
                          | 'top-right'
                          | 'bottom-left'
                          | 'bottom-right'
                        )
                      | null;
                    /**
                     * Hex color code (e.g., #000000)
                     */
                    startColor?: string | null;
                    /**
                     * Hex color code (e.g., #ffffff)
                     */
                    endColor?: string | null;
                    /**
                     * Gradient opacity (0 = transparent, 1 = opaque)
                     */
                    opacity?: number | null;
                  };
                  /**
                   * Mark this column as "Coming Soon" - will fade out and disable clicking
                   */
                  comingSoon?: boolean | null;
                  link: {
                    /**
                     * Select the tenant to link to. URL will be generated automatically based on environment.
                     */
                    tenant?: (number | null) | Tenant;
                    text: string;
                    openInNewTab?: boolean | null;
                  };
                  /**
                   * Optional social network links for this column
                   */
                  socialNetworks?: {
                    /**
                     * Full Facebook profile or page URL
                     */
                    facebook?: string | null;
                    /**
                     * Full Instagram profile URL
                     */
                    instagram?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'three-columns';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
            };
            mediaTopRight?: (number | null) | Media;
            mediaBottomLeft?: (number | null) | Media;
            mediaBottomRight?: (number | null) | Media;
            /**
             * Adjust vertical parallax in percent of the element height. Negative moves up, positive moves down.
             */
            parallax?: {
              topRight?: number | null;
              bottomLeft?: number | null;
              bottomRight?: number | null;
            };
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'botique-intro';
          }
        | {
            headingEyebrow?: string | null;
            heading: string;
            leftText?: string | null;
            address?: string | null;
            email?: string | null;
            phone?: string | null;
            form: number | Form;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'boutique-contact';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Add rooms (e.g., Premium, Deluxe, Suite, Apartment)
             */
            rooms?:
              | {
                  /**
                   * Rentlio properties are loading… If this remains a plain input, enter the ID manually or fix the API credentials.
                   */
                  rentlioPropertyId?: string | null;
                  /**
                   * Sales channels are loading… If this remains a plain input, enter the ID manually or fix the API credentials.
                   */
                  rentlioSalesChannelId?: string | null;
                  /**
                   * Optional. Select a unit type to enable Rentlio bookings for this room. Leave empty if the room is informational only.
                   */
                  rentlioUnitTypeId?: string | null;
                  title: string;
                  description?: string | null;
                  badges?:
                    | {
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  images?:
                    | {
                        image: number | Media;
                        alt?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rooms';
          }
        | {
            heading: string;
            images?:
              | {
                  media: number | Media;
                  alt?: string | null;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Higher = slower. Animation speeds up temporarily with scroll velocity.
             */
            baseDuration?: number | null;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rooftop';
          }
        | {
            heading: string;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rooftop-features';
          }
        | {
            /**
             * Main title for the location section
             */
            title: string;
            /**
             * Short description about the location
             */
            description?: string | null;
            /**
             * Full address for the location
             */
            address: string;
            coordinates: {
              /**
               * Latitude coordinate for the map pin
               */
              lat: number;
              /**
               * Longitude coordinate for the map pin
               */
              lng: number;
            };
            workingHours?:
              | {
                  day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
                  isOpen?: boolean | null;
                  /**
                   * Format: HH:MM (e.g., 09:00)
                   */
                  openTime?: string | null;
                  /**
                   * Format: HH:MM (e.g., 18:00)
                   */
                  closeTime?: string | null;
                  isClosed?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'location';
          }
        | {
            title: string;
            subtitle?: string | null;
            popularBadgeText: string;
            menuCategories?:
              | {
                  categoryName: string;
                  categoryDescription?: string | null;
                  categoryImage: number | Media;
                  menuItems?:
                    | {
                        itemName: string;
                        itemDescription?: string | null;
                        itemPrice?: string | null;
                        isPopular?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for this section (used for navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'concept-bar-menu';
          }
        | {
            title: string;
            subtitle?: string | null;
            description: string;
            buttonText: string;
            buttonUrl: string;
            badgeText: string;
            features?:
              | {
                  featureText: string;
                  id?: string | null;
                }[]
              | null;
            ctaNote: string;
            /**
             * Optional background image for the block
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Optional ID for this section (used for navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'job-opportunity';
          }
        | {
            media: number | Media;
            alt?: string | null;
            caption?: string | null;
            layout?: ('full' | 'contained') | null;
            align?: ('left' | 'center' | 'right') | null;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            /**
             * Enter the intro text that will be displayed centered in black
             */
            content: string;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro';
          }
        | {
            /**
             * Main title displayed in the center
             */
            title: string;
            /**
             * Subtitle text displayed below the title
             */
            subtitle: string;
            /**
             * Optional button text (e.g., "Reservieren")
             */
            buttonText?: string | null;
            /**
             * URL for the button (if button text is provided)
             */
            buttonUrl?: string | null;
            /**
             * Momento landing: 6 slika za galeriju „Prostor” (1–4 interijer/terasa, 5–6 atmosfera/karijera). Ostali tenanti: 4 dovoljno.
             */
            images?:
              | {
                  image: number | Media;
                  /**
                   * Choose the position and aspect ratio for this image
                   */
                  position: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for this section (used for menu navigation)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-grid';
          }
        | {
            /**
             * Optional heading above the floor plan
             */
            title?: string | null;
            /**
             * Building with floor plan image and unit regions
             */
            building: number | Building;
            /**
             * Optional ID for anchor links
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'floor-plan';
          }
        | RealEstateLandingNavBlock
        | RealEstateLandingHeroBlock
        | RealEstateLandingMarqueeBlock
        | RealEstateLandingManifestoBlock
        | RealEstateLandingTypologyBlock
        | RealEstateLandingGalleryBlock
        | RealEstateLandingCurrentProjectBlock
        | RealEstateLandingPartnerBlock
        | RealEstateLandingInquiryBlock
        | RealEstateLandingUnitBrowserBlock
        | RealEstateLandingPastProjectsBlock
        | {
            heading: string;
            subheading?: string | null;
            /**
             * Optional hero background image
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Optional ID for anchor links (e.g. hero)
             */
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-estate-hero';
          }
        | {
            /**
             * Small label above the heading
             */
            eyebrow?: string | null;
            heading: string;
            /**
             * HTML allowed (e.g. <p>...</p>)
             */
            body: string;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-estate-about-us';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            subtitle?: string | null;
            projects?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  location?: string | null;
                  year?: string | null;
                  galleryImages?:
                    | {
                        image: number | Media;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-estate-projects-we-did';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            subtitle?: string | null;
            projects?:
              | {
                  /**
                   * Floor plan and units are defined on the Building. Opening this project on the site shows the plan; tap a unit to open its PDF page.
                   */
                  building?: (number | null) | Building;
                  title: string;
                  /**
                   * Shown on the project card and in the drawer.
                   */
                  description?: string | null;
                  /**
                   * Thumbnail on the project card (grid).
                   */
                  image?: (number | null) | Media;
                  status?: string | null;
                  ctaText?: string | null;
                  ctaUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-estate-current-projects';
          }
        | {
            heading: string;
            subtitle?: string | null;
            /**
             * YouTube embed URL, Vimeo, or iframe src. Leave empty for placeholder.
             */
            streamUrl?: string | null;
            /**
             * Shown when no stream URL is set
             */
            fallbackImage?: (number | null) | Media;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-estate-live-camera';
          }
        | {
            badge?: string | null;
            heading: string;
            subtitle?: string | null;
            description: string;
            features?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            buttonText: string;
            buttonUrl: string;
            ctaNote?: string | null;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-estate-looking-for-job';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            leftText?: string | null;
            address?: string | null;
            email?: string | null;
            phone?: string | null;
            sectionId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-estate-contact';
          }
        | {
            /**
             * ID used as the scroll target (e.g. "contact" → links to #contact). Use lowercase letters, numbers, and dashes.
             */
            anchorId: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'anchor';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable form definitions (e.g. blocks that reference a form ID). The Real Estate landing contact section is the “RE Landing — Inquiry” block in Pages → layout — configure labels and POST URL there, not here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One building = one floor plan image + one unit-details PDF (e.g. STANOVI.pdf). Draw each unit on the plan, then set label (e.g. A.1.2) and PDF page number for each.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buildings".
 */
export interface Building {
  id: number;
  /**
   * e.g. "Building A", "Dilatacija A"
   */
  title: string;
  /**
   * Floor plan as image (PNG/JPG). If you have a PDF, export the first page as image. Save this document after uploading so you can draw units below.
   */
  floorPlanImage: number | Media;
  /**
   * e.g. STANOVI.pdf — page 1 = first unit, page 2 = second, etc. Upload under Media & Assets → Documents, then select here.
   */
  unitDetailsPdf: number | Document;
  /**
   * Each row = one unit (e.g. A.1.1). Draw regions on the plan above. Counts per floor on the site come from this list. Status (Available / Reserved / Sold) is edited here — PDF re-seed keeps Reserved/Sold when the unit label matches.
   */
  units?:
    | {
        /**
         * e.g. "A.1.1", "DVOSOBNI STAN A.1.1"
         */
        label: string;
        /**
         * Page number in Unit details PDF (1 = first page)
         */
        detailPageNumber: number;
        /**
         * Letter or code (e.g. A, B) for grouping in the unit browser.
         */
        dilatacija?: string | null;
        /**
         * Floor number for filtering (e.g. 0 = ground, 1 = first).
         */
        floor?: number | null;
        unitType?:
          | (
              | 'garsonijera'
              | 'jednosobni'
              | 'jednoipolsobni'
              | 'dvosobni'
              | 'dvoipolsobni'
              | 'trosobni'
              | 'penthouse'
              | 'other'
            )
          | null;
        netArea?: number | null;
        grossArea?: number | null;
        /**
         * Shown on the landing unit cards (green / amber / red). Default Available for new units.
         */
        status?: ('available' | 'reserved' | 'sold') | null;
        /**
         * Polygon: draw by clicking points on the plan, then "Complete unit".
         */
        shape: {
          /**
           * Points (x,y %). Filled by drawing on the plan.
           */
          points: {
            /**
             * x %
             */
            x: number;
            /**
             * y %
             */
            y: number;
            id?: string | null;
          }[];
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingNavBlock".
 */
export interface RealEstateLandingNavBlock {
  /**
   * Small HTML snippet for the logo area.
   */
  brandHtml?: string | null;
  /**
   * Accessibility label for the brand link (e.g. “District home”).
   */
  brandAriaLabel?: string | null;
  langLine?: string | null;
  showLangLine?: boolean | null;
  /**
   * In-page anchors (#section) or full URLs.
   */
  links?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional call-to-action in the nav bar.
   */
  ctaLabel?: string | null;
  ctaHref?: string | null;
  ctaOpenInNewTab?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-nav';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingHeroBlock".
 */
export interface RealEstateLandingHeroBlock {
  /**
   * HTML id for “back to top” / first screen (default: top).
   */
  heroSectionId?: string | null;
  layout?: ('default' | 'split' | 'centered') | null;
  /**
   * Small meta lines (e.g. city, coordinates).
   */
  topLeftLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  topRightLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  eyebrow: string;
  titleLine1: string;
  /**
   * Optional second line (e.g. italic name).
   */
  titleLine2Html?: string | null;
  heroImage: number | Media;
  /**
   * Accessibility: short description of the image for screen readers.
   */
  imageAlt?: string | null;
  mediaCaption?: string | null;
  lead: string;
  showScrollCue?: boolean | null;
  scrollCueLabel?: string | null;
  /**
   * Short label + value pairs under the hero.
   */
  metaRows?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingMarqueeBlock".
 */
export interface RealEstateLandingMarqueeBlock {
  /**
   * Lower = faster scroll.
   */
  durationSeconds?: number | null;
  /**
   * Single character or short symbol between phrases.
   */
  separator?: string | null;
  /**
   * Describe the ticker for screen readers.
   */
  ariaLabel?: string | null;
  items?:
    | {
        text: string;
        italic?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingManifestoBlock".
 */
export interface RealEstateLandingManifestoBlock {
  /**
   * HTML id for in-page links, e.g. kat, kontakt
   */
  sectionId?: string | null;
  labelLeft: string;
  labelNum: string;
  /**
   * Optional short paragraph before the big type.
   */
  topIntroHtml?: string | null;
  /**
   * Each row = sequence of segments (plain / muted / accent).
   */
  rows?:
    | {
        segments?:
          | {
              text: string;
              style?: ('plain' | 'mute' | 'accent') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional small print under the statement.
   */
  footnoteHtml?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-manifesto';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingTypologyBlock".
 */
export interface RealEstateLandingTypologyBlock {
  /**
   * HTML id for in-page links, e.g. kat, kontakt
   */
  sectionId?: string | null;
  eyebrow: string;
  /**
   * Build the main heading from ordered fragments (plain or italic).
   */
  headingParts?:
    | {
        text: string;
        italic?: boolean | null;
        lineBreak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  intro: string;
  /**
   * Shown after the count in each row (e.g. “units”, “stanova”). Leave empty for default “stanova”.
   */
  countSuffixWord?: string | null;
  /**
   * Shown below the table when set.
   */
  outroHtml?: string | null;
  items?:
    | {
        unitCode: string;
        name: string;
        size: string;
        description: string;
        count: number;
        /**
         * Optional emphasis in the list UI.
         */
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-typology';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingGalleryBlock".
 */
export interface RealEstateLandingGalleryBlock {
  /**
   * HTML id for in-page links, e.g. kat, kontakt
   */
  sectionId?: string | null;
  eyebrow: string;
  /**
   * Build the main heading from ordered fragments (plain or italic).
   */
  headingParts?:
    | {
        text: string;
        italic?: boolean | null;
        lineBreak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Fallback text beside the heading. Ignored when “Intro (HTML)” is filled.
   */
  intro: string;
  /**
   * When set, replaces the plain intro next to the heading.
   */
  introHtml?: string | null;
  slides?:
    | {
        image: number | Media;
        /**
         * Overrides default alt (slide title) for accessibility.
         */
        slideImageAlt?: string | null;
        name: string;
        location: string;
        credit?: string | null;
        /**
         * Wraps the slide in a link when set.
         */
        linkUrl?: string | null;
        linkOpenInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingCurrentProjectBlock".
 */
export interface RealEstateLandingCurrentProjectBlock {
  /**
   * HTML id for in-page links, e.g. kat, kontakt
   */
  sectionId?: string | null;
  eyebrow: string;
  /**
   * Build the main heading from ordered fragments (plain or italic).
   */
  headingParts?:
    | {
        text: string;
        italic?: boolean | null;
        lineBreak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  bigNumber: string;
  projectMeta: string;
  projectNameHtml: string;
  description: string;
  image: number | Media;
  /**
   * Accessibility: short description of the image for screen readers.
   */
  imageAlt?: string | null;
  ctaLabel: string;
  ctaHref: string;
  ctaOpenInNewTab?: boolean | null;
  /**
   * Three-ish columns under the image.
   */
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-current-project';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingPartnerBlock".
 */
export interface RealEstateLandingPartnerBlock {
  /**
   * HTML id for in-page links, e.g. kat, kontakt
   */
  sectionId?: string | null;
  image: number | Media;
  /**
   * Accessibility: short description of the image for screen readers.
   */
  imageAlt?: string | null;
  eyebrow: string;
  /**
   * Build the main heading from ordered fragments (plain or italic).
   */
  headingParts?:
    | {
        text: string;
        italic?: boolean | null;
        lineBreak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel: string;
  ctaHref: string;
  ctaOpenInNewTab?: boolean | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  secondaryCtaOpenInNewTab?: boolean | null;
  signatureBold: string;
  signatureSub: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-partner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingInquiryBlock".
 */
export interface RealEstateLandingInquiryBlock {
  /**
   * HTML id for in-page links, e.g. kat, kontakt
   */
  sectionId?: string | null;
  eyebrow: string;
  /**
   * Build the main heading from ordered fragments (plain or italic).
   */
  headingParts?:
    | {
        text: string;
        italic?: boolean | null;
        lineBreak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. One short paragraph between the headline and the form fields.
   */
  introHtml?: string | null;
  /**
   * POST endpoint where the browser submits the form (Formspark, Basin, Getform, …). If empty here, the public site uses the default URL from Menu → “RE landing — form & footer defaults” for this tenant. This block is not the Forms collection — edit under Pages → layout.
   */
  formActionUrl?: string | null;
  formMethod?: ('POST' | 'GET') | null;
  submitButtonLabel?: string | null;
  disabledSubmitHelp?: string | null;
  nameFieldLabel?: string | null;
  emailFieldLabel?: string | null;
  phoneFieldLabel?: string | null;
  interestFieldLabel?: string | null;
  messageFieldLabel?: string | null;
  interestPlaceholder?: string | null;
  messagePlaceholder?: string | null;
  /**
   * Shown below the form fields, above the four contact cells (matches landing layout).
   */
  privacyHtml?: string | null;
  interestOptions?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  contacts?:
    | {
        label: string;
        valueHtml: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-inquiry';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingUnitBrowserBlock".
 */
export interface RealEstateLandingUnitBrowserBlock {
  /**
   * HTML id for in-page links, e.g. kat, kontakt
   */
  sectionId?: string | null;
  eyebrow: string;
  /**
   * Build the main heading from ordered fragments (plain or italic).
   */
  headingParts?:
    | {
        text: string;
        italic?: boolean | null;
        lineBreak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  introHtml: string;
  /**
   * Optional copy next to the intro (e.g. colour dots for sold/reserved).
   */
  legendHtml?: string | null;
  /**
   * Replaces the default “click unit for PDF” hint when set.
   */
  detailPanelNoteHtml?: string | null;
  /**
   * Must include unitDetailsPdf and units with floor/dilatacija for filters.
   */
  building: number | Building;
  /**
   * Optional line above unit title in PDF modal, e.g. project name.
   */
  pdfMetaLine?: string | null;
  /**
   * Leave empty to use Croatian defaults. Fill for EN/DE or custom wording — all managed in CMS.
   */
  browserCopy?: {
    dilatationLabel?: string | null;
    floorLabel?: string | null;
    floorButtonWord?: string | null;
    stageFloorWord?: string | null;
    unitsTotalSuffix?: string | null;
    /**
     * Before letter, e.g. "· Dilatacija " (space at end).
     */
    dilatationStagePrefix?: string | null;
    statusAvailable?: string | null;
    statusReserved?: string | null;
    statusSold?: string | null;
    loadingInProgress?: string | null;
    /**
     * HTTP status inserted at {status}.
     */
    loadingErrorTemplate?: string | null;
    pdfCardBadge?: string | null;
    adminHint?: string | null;
    defaultDetailLead?: string | null;
    /**
     * Example: Pages {from}–{to}.
     */
    pagesRangeTemplate?: string | null;
    unexpectedResponse?: string | null;
    networkFailure?: string | null;
  };
  pdfModalCopy?: {
    /**
     * Use placeholders {dil} and {floor}. Shown when “PDF modal meta line” is empty.
     */
    metaTemplate?: string | null;
    closeLabel?: string | null;
    modalUnitWord?: string | null;
    netLabel?: string | null;
    grossLabel?: string | null;
    pdfPagePrefix?: string | null;
    emptyDocumentMessage?: string | null;
    openInNewTab?: string | null;
    sendInquiryCta?: string | null;
    embedTitleTemplate?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-unit-browser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingPastProjectsBlock".
 */
export interface RealEstateLandingPastProjectsBlock {
  /**
   * HTML id for in-page links, e.g. kat, kontakt
   */
  sectionId?: string | null;
  layout?: ('rows' | 'grid') | null;
  eyebrow: string;
  /**
   * Build the main heading from ordered fragments (plain or italic).
   */
  headingParts?:
    | {
        text: string;
        italic?: boolean | null;
        lineBreak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  introHtml: string;
  projects?:
    | {
        name: string;
        subtitle?: string | null;
        location: string;
        year: string;
        statusLabel: string;
        statusActive?: boolean | null;
        /**
         * Shown in grid cards under the title (optional).
         */
        summaryHtml?: string | null;
        externalUrl?: string | null;
        externalOpenInNewTab?: boolean | null;
        previewImage?: (number | null) | Media;
        previewImageAlt?: string | null;
        gallery?:
          | {
              image: number | Media;
              caption?: string | null;
              alt?: string | null;
              credit?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'real-estate-landing-past-projects';
}
/**
 * Manage navigation menus for tenants and main domain
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  /**
   * Unique identifier for this menu type. Main Menu gets centered logo styling, Tenant Menu gets standard top-left styling.
   */
  identifier: 'main-menu' | 'tenant-menu';
  /**
   * Internal title for this menu (e.g., "Hotel ABC Menu", "Restaurant XYZ Menu")
   */
  title: string;
  tenant?: (number | null) | Tenant;
  menuItems?:
    | {
        label: string;
        /**
         * URL or path for this menu item (required even if using scroll target)
         */
        link: string;
        /**
         * Optional section ID to scroll to (e.g., "hero", "features"). Leave empty to use the link above.
         */
        scrollTarget?: string | null;
        external?: boolean | null;
        children?:
          | {
              label: string;
              /**
               * URL or path for this menu item (required even if using scroll target)
               */
              link: string;
              /**
               * Optional section ID to scroll to (e.g., "hero", "features"). Leave empty to use the link above.
               */
              scrollTarget?: string | null;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  logoText?: string | null;
  /**
   * Center line on the main-domain triptych home (e.g. Osijek · Slavonia · MMXXVI). Shown only when the first page block is three columns.
   */
  hubTagline?: string | null;
  /**
   * Used on the public site when “RE Landing — Inquiry” has an empty Form action URL (one endpoint per menu). Footer stays on the page layout block only.
   */
  reLandingDefaults?: {
    /**
     * Formspark, Basin, Getform, or your endpoint. Applied when the Inquiry block’s “Form action URL” is empty.
     */
    formActionUrl?: string | null;
    formMethod?: ('POST' | 'GET') | null;
  };
  /**
   * Choose how the menu should be positioned on the page
   */
  positioning?: ('fixed' | 'absolute' | 'relative') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-tenant marketing footer (multi-column). Used on the public site for tenant pages, including RE landing. Suggested first line in Main heading: your brand, then a line with tenant name · subdomain · Real Estate.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Internal title for this footer (e.g., "Hotel ABC Footer", "Restaurant XYZ Footer")
   */
  title: string;
  /**
   * Which organization this footer belongs to. Content (headings, address, links) should match that tenant.
   */
  tenant?: (number | null) | Tenant;
  leftContent: {
    /**
     * RE landing: usually one line with <b>district.</b> (HTML allowed). Boutique/other: brand headline.
     */
    heading: string;
    /**
     * RE landing: second line under the brand, e.g. Tenant name · subdomain · Real Estate (plain text).
     */
    subheading?: string | null;
  };
  rightContent: {
    contact: {
      heading: string;
      email: string;
      phone?: string | null;
      /**
       * Enter without @ symbol (e.g., legendslounge)
       */
      instagram?: string | null;
    };
    address: {
      heading: string;
      venue: string;
      street: string;
      city: string;
      country: string;
    };
  };
  /**
   * RE landing: copyright (left), optional links (next to ©), optional right tail. Matches District footer bar.
   */
  bottomContent: {
    copyright: string;
    links?:
      | {
          text: string;
          url: string;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * RE landing: small caps line on the bottom-right (e.g. credits). Leave empty to hide.
     */
    madeBy?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'menu';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'buildings';
        value: number | Building;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        xs?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xxl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait34?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        landscape43?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        landscape169?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  subdomain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tenant?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundMedia?:
                | T
                | {
                    type?: T;
                    image?: T;
                    video?: T;
                    overlay?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              fontSize?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'three-columns'?:
          | T
          | {
              columns?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    kicker?: T;
                    numberLabel?: T;
                    titleItalic?: T;
                    backgroundImage?: T;
                    fullHeight?: T;
                    gradient?:
                      | T
                      | {
                          enabled?: T;
                          type?: T;
                          direction?: T;
                          position?: T;
                          startColor?: T;
                          endColor?: T;
                          opacity?: T;
                        };
                    comingSoon?: T;
                    link?:
                      | T
                      | {
                          tenant?: T;
                          text?: T;
                          openInNewTab?: T;
                        };
                    socialNetworks?:
                      | T
                      | {
                          facebook?: T;
                          instagram?: T;
                        };
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'botique-intro'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              mediaTopRight?: T;
              mediaBottomLeft?: T;
              mediaBottomRight?: T;
              parallax?:
                | T
                | {
                    topRight?: T;
                    bottomLeft?: T;
                    bottomRight?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'boutique-contact'?:
          | T
          | {
              headingEyebrow?: T;
              heading?: T;
              leftText?: T;
              address?: T;
              email?: T;
              phone?: T;
              form?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        rooms?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              rooms?:
                | T
                | {
                    rentlioPropertyId?: T;
                    rentlioSalesChannelId?: T;
                    rentlioUnitTypeId?: T;
                    title?: T;
                    description?: T;
                    badges?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    images?:
                      | T
                      | {
                          image?: T;
                          alt?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        rooftop?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    media?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              baseDuration?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'rooftop-features'?:
          | T
          | {
              heading?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        location?:
          | T
          | {
              title?: T;
              description?: T;
              address?: T;
              coordinates?:
                | T
                | {
                    lat?: T;
                    lng?: T;
                  };
              workingHours?:
                | T
                | {
                    day?: T;
                    isOpen?: T;
                    openTime?: T;
                    closeTime?: T;
                    isClosed?: T;
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'concept-bar-menu'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              popularBadgeText?: T;
              menuCategories?:
                | T
                | {
                    categoryName?: T;
                    categoryDescription?: T;
                    categoryImage?: T;
                    menuItems?:
                      | T
                      | {
                          itemName?: T;
                          itemDescription?: T;
                          itemPrice?: T;
                          isPopular?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'job-opportunity'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              badgeText?: T;
              features?:
                | T
                | {
                    featureText?: T;
                    id?: T;
                  };
              ctaNote?: T;
              backgroundImage?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              media?: T;
              alt?: T;
              caption?: T;
              layout?: T;
              align?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        intro?:
          | T
          | {
              content?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'image-grid'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonText?: T;
              buttonUrl?: T;
              images?:
                | T
                | {
                    image?: T;
                    position?: T;
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'floor-plan'?:
          | T
          | {
              title?: T;
              building?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'real-estate-landing-nav'?: T | RealEstateLandingNavBlockSelect<T>;
        'real-estate-landing-hero'?: T | RealEstateLandingHeroBlockSelect<T>;
        'real-estate-landing-marquee'?: T | RealEstateLandingMarqueeBlockSelect<T>;
        'real-estate-landing-manifesto'?: T | RealEstateLandingManifestoBlockSelect<T>;
        'real-estate-landing-typology'?: T | RealEstateLandingTypologyBlockSelect<T>;
        'real-estate-landing-gallery'?: T | RealEstateLandingGalleryBlockSelect<T>;
        'real-estate-landing-current-project'?: T | RealEstateLandingCurrentProjectBlockSelect<T>;
        'real-estate-landing-partner'?: T | RealEstateLandingPartnerBlockSelect<T>;
        'real-estate-landing-inquiry'?: T | RealEstateLandingInquiryBlockSelect<T>;
        'real-estate-landing-unit-browser'?: T | RealEstateLandingUnitBrowserBlockSelect<T>;
        'real-estate-landing-past-projects'?: T | RealEstateLandingPastProjectsBlockSelect<T>;
        'real-estate-hero'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'real-estate-about-us'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'real-estate-projects-we-did'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtitle?: T;
              projects?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    location?: T;
                    year?: T;
                    galleryImages?:
                      | T
                      | {
                          image?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'real-estate-current-projects'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtitle?: T;
              projects?:
                | T
                | {
                    building?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    status?: T;
                    ctaText?: T;
                    ctaUrl?: T;
                    id?: T;
                  };
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'real-estate-live-camera'?:
          | T
          | {
              heading?: T;
              subtitle?: T;
              streamUrl?: T;
              fallbackImage?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'real-estate-looking-for-job'?:
          | T
          | {
              badge?: T;
              heading?: T;
              subtitle?: T;
              description?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonUrl?: T;
              ctaNote?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        'real-estate-contact'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              leftText?: T;
              address?: T;
              email?: T;
              phone?: T;
              sectionId?: T;
              id?: T;
              blockName?: T;
            };
        anchor?:
          | T
          | {
              anchorId?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingNavBlock_select".
 */
export interface RealEstateLandingNavBlockSelect<T extends boolean = true> {
  brandHtml?: T;
  brandAriaLabel?: T;
  langLine?: T;
  showLangLine?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  ctaOpenInNewTab?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingHeroBlock_select".
 */
export interface RealEstateLandingHeroBlockSelect<T extends boolean = true> {
  heroSectionId?: T;
  layout?: T;
  topLeftLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  topRightLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  eyebrow?: T;
  titleLine1?: T;
  titleLine2Html?: T;
  heroImage?: T;
  imageAlt?: T;
  mediaCaption?: T;
  lead?: T;
  showScrollCue?: T;
  scrollCueLabel?: T;
  metaRows?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingMarqueeBlock_select".
 */
export interface RealEstateLandingMarqueeBlockSelect<T extends boolean = true> {
  durationSeconds?: T;
  separator?: T;
  ariaLabel?: T;
  items?:
    | T
    | {
        text?: T;
        italic?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingManifestoBlock_select".
 */
export interface RealEstateLandingManifestoBlockSelect<T extends boolean = true> {
  sectionId?: T;
  labelLeft?: T;
  labelNum?: T;
  topIntroHtml?: T;
  rows?:
    | T
    | {
        segments?:
          | T
          | {
              text?: T;
              style?: T;
              id?: T;
            };
        id?: T;
      };
  footnoteHtml?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingTypologyBlock_select".
 */
export interface RealEstateLandingTypologyBlockSelect<T extends boolean = true> {
  sectionId?: T;
  eyebrow?: T;
  headingParts?:
    | T
    | {
        text?: T;
        italic?: T;
        lineBreak?: T;
        id?: T;
      };
  intro?: T;
  countSuffixWord?: T;
  outroHtml?: T;
  items?:
    | T
    | {
        unitCode?: T;
        name?: T;
        size?: T;
        description?: T;
        count?: T;
        highlight?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingGalleryBlock_select".
 */
export interface RealEstateLandingGalleryBlockSelect<T extends boolean = true> {
  sectionId?: T;
  eyebrow?: T;
  headingParts?:
    | T
    | {
        text?: T;
        italic?: T;
        lineBreak?: T;
        id?: T;
      };
  intro?: T;
  introHtml?: T;
  slides?:
    | T
    | {
        image?: T;
        slideImageAlt?: T;
        name?: T;
        location?: T;
        credit?: T;
        linkUrl?: T;
        linkOpenInNewTab?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingCurrentProjectBlock_select".
 */
export interface RealEstateLandingCurrentProjectBlockSelect<T extends boolean = true> {
  sectionId?: T;
  eyebrow?: T;
  headingParts?:
    | T
    | {
        text?: T;
        italic?: T;
        lineBreak?: T;
        id?: T;
      };
  bigNumber?: T;
  projectMeta?: T;
  projectNameHtml?: T;
  description?: T;
  image?: T;
  imageAlt?: T;
  ctaLabel?: T;
  ctaHref?: T;
  ctaOpenInNewTab?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingPartnerBlock_select".
 */
export interface RealEstateLandingPartnerBlockSelect<T extends boolean = true> {
  sectionId?: T;
  image?: T;
  imageAlt?: T;
  eyebrow?: T;
  headingParts?:
    | T
    | {
        text?: T;
        italic?: T;
        lineBreak?: T;
        id?: T;
      };
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  ctaOpenInNewTab?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  secondaryCtaOpenInNewTab?: T;
  signatureBold?: T;
  signatureSub?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingInquiryBlock_select".
 */
export interface RealEstateLandingInquiryBlockSelect<T extends boolean = true> {
  sectionId?: T;
  eyebrow?: T;
  headingParts?:
    | T
    | {
        text?: T;
        italic?: T;
        lineBreak?: T;
        id?: T;
      };
  introHtml?: T;
  formActionUrl?: T;
  formMethod?: T;
  submitButtonLabel?: T;
  disabledSubmitHelp?: T;
  nameFieldLabel?: T;
  emailFieldLabel?: T;
  phoneFieldLabel?: T;
  interestFieldLabel?: T;
  messageFieldLabel?: T;
  interestPlaceholder?: T;
  messagePlaceholder?: T;
  privacyHtml?: T;
  interestOptions?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contacts?:
    | T
    | {
        label?: T;
        valueHtml?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingUnitBrowserBlock_select".
 */
export interface RealEstateLandingUnitBrowserBlockSelect<T extends boolean = true> {
  sectionId?: T;
  eyebrow?: T;
  headingParts?:
    | T
    | {
        text?: T;
        italic?: T;
        lineBreak?: T;
        id?: T;
      };
  introHtml?: T;
  legendHtml?: T;
  detailPanelNoteHtml?: T;
  building?: T;
  pdfMetaLine?: T;
  browserCopy?:
    | T
    | {
        dilatationLabel?: T;
        floorLabel?: T;
        floorButtonWord?: T;
        stageFloorWord?: T;
        unitsTotalSuffix?: T;
        dilatationStagePrefix?: T;
        statusAvailable?: T;
        statusReserved?: T;
        statusSold?: T;
        loadingInProgress?: T;
        loadingErrorTemplate?: T;
        pdfCardBadge?: T;
        adminHint?: T;
        defaultDetailLead?: T;
        pagesRangeTemplate?: T;
        unexpectedResponse?: T;
        networkFailure?: T;
      };
  pdfModalCopy?:
    | T
    | {
        metaTemplate?: T;
        closeLabel?: T;
        modalUnitWord?: T;
        netLabel?: T;
        grossLabel?: T;
        pdfPagePrefix?: T;
        emptyDocumentMessage?: T;
        openInNewTab?: T;
        sendInquiryCta?: T;
        embedTitleTemplate?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RealEstateLandingPastProjectsBlock_select".
 */
export interface RealEstateLandingPastProjectsBlockSelect<T extends boolean = true> {
  sectionId?: T;
  layout?: T;
  eyebrow?: T;
  headingParts?:
    | T
    | {
        text?: T;
        italic?: T;
        lineBreak?: T;
        id?: T;
      };
  introHtml?: T;
  projects?:
    | T
    | {
        name?: T;
        subtitle?: T;
        location?: T;
        year?: T;
        statusLabel?: T;
        statusActive?: T;
        summaryHtml?: T;
        externalUrl?: T;
        externalOpenInNewTab?: T;
        previewImage?: T;
        previewImageAlt?: T;
        gallery?:
          | T
          | {
              image?: T;
              caption?: T;
              alt?: T;
              credit?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  identifier?: T;
  title?: T;
  tenant?: T;
  menuItems?:
    | T
    | {
        label?: T;
        link?: T;
        scrollTarget?: T;
        external?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              scrollTarget?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  logo?: T;
  logoText?: T;
  hubTagline?: T;
  reLandingDefaults?:
    | T
    | {
        formActionUrl?: T;
        formMethod?: T;
      };
  positioning?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  tenant?: T;
  leftContent?:
    | T
    | {
        heading?: T;
        subheading?: T;
      };
  rightContent?:
    | T
    | {
        contact?:
          | T
          | {
              heading?: T;
              email?: T;
              phone?: T;
              instagram?: T;
            };
        address?:
          | T
          | {
              heading?: T;
              venue?: T;
              street?: T;
              city?: T;
              country?: T;
            };
      };
  bottomContent?:
    | T
    | {
        copyright?: T;
        links?:
          | T
          | {
              text?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        madeBy?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buildings_select".
 */
export interface BuildingsSelect<T extends boolean = true> {
  title?: T;
  floorPlanImage?: T;
  unitDetailsPdf?: T;
  units?:
    | T
    | {
        label?: T;
        detailPageNumber?: T;
        dilatacija?: T;
        floor?: T;
        unitType?: T;
        netArea?: T;
        grossArea?: T;
        status?: T;
        shape?:
          | T
          | {
              points?:
                | T
                | {
                    x?: T;
                    y?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}